version: "3.8"

services:
  ggportal-front:
    container_name: ggportal-front
    image: arm32v7/ggportal-front:latest
    volumes:
      - ./front/nginx/lalainaetguillaume.zapto.org.conf:/etc/nginx/conf.d/lalainaetguillaume.zapto.org.conf
      - ./front/nginx/certbot/conf:/etc/letsencrypt
      - ./front/nginx/certbot/www:/var/www/certbot
      - storage:/usr/share/nginx/html/storage
    ports:
      - 80:80
      - 443:443
    networks:
      - gg-application
    depends_on:
      - ggportal-back

  ggportal-certbot:
    container_name: ggportal-certbot
    image: certbot/certbot:arm32v6-latest
    volumes:
      - ./front/nginx/certbot/conf:/etc/letsencrypt
      - ./front/nginx/certbot/www:/var/www/certbot
    networks:
      - gg-application

  ggportal-back:
    container_name: ggportal-back
    image: arm32v7/ggportal-back:latest
    volumes:
      - ./back/conf/application.properties:/application-prod.properties:ro
      - storage:/storage
    ports:
      - 8080:8080
    networks:
      - gg-application
    depends_on:
      - ggportal-db
  
  ggportal-db:
    container_name: ggportal-db
    image: arm32v7/postgres:13-alpine
    environment:
      - POSTGRES_DB=db_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superSecuredPassword
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - gg-application

  ggportal-adminer:
    container_name: ggportal-adminer
    image: arm32v7/adminer
    ports:
      - 8090:8080
    networks:
      - gg-application

volumes:
  storage:
    external: true

networks:
  gg-application:
    external:
      name: gg-application
