version: "3.8"

services:
  ggportal-front:
    container_name: ggportal-front
    image: registry.gitlab.com/shulkio/ggportal-front:dev
    volumes:
      - ./front/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ggportal-back

  ggportal-back:
    container_name: ggportal-back
    image: registry.gitlab.com/shulkio/ggportal-back:dev
    volumes:
      - ./back/conf/application.properties:/application.properties:ro
    ports:
      - 8080:8080
    depends_on:
      - ggportal-db
  
  ggportal-db:
    container_name: ggportal-db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superSecuredPassword
    volumes:
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  ggportal-adminer:
    container_name: ggportal-adminer
    image: adminer
    ports:
      - 8070:8080
